// Code generated by radius-dict-gen. DO NOT EDIT.

package unix

import (
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_Unix_VendorID = 4
)

func _Unix_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_Unix_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _Unix_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Unix_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Unix_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _Unix_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _Unix_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Unix_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _Unix_AddVendor(p, typ, attr)
}

func _Unix_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _Unix_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

type UnixFTPUID uint32

var UnixFTPUID_Strings = map[UnixFTPUID]string{}

func (a UnixFTPUID) String() string {
	if str, ok := UnixFTPUID_Strings[a]; ok {
		return str
	}
	return "UnixFTPUID(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func UnixFTPUID_Add(p *radius.Packet, value UnixFTPUID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Unix_AddVendor(p, 10, a)
}

func UnixFTPUID_Get(p *radius.Packet) (value UnixFTPUID) {
	value, _ = UnixFTPUID_Lookup(p)
	return
}

func UnixFTPUID_Gets(p *radius.Packet) (values []UnixFTPUID, err error) {
	var i uint32
	for _, attr := range _Unix_GetsVendor(p, 10) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, UnixFTPUID(i))
	}
	return
}

func UnixFTPUID_Lookup(p *radius.Packet) (value UnixFTPUID, err error) {
	a, ok := _Unix_LookupVendor(p, 10)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = UnixFTPUID(i)
	return
}

func UnixFTPUID_Set(p *radius.Packet, value UnixFTPUID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Unix_SetVendor(p, 10, a)
}

func UnixFTPUID_Del(p *radius.Packet) {
	_Unix_DelVendor(p, 10)
}

type UnixFTPGID uint32

var UnixFTPGID_Strings = map[UnixFTPGID]string{}

func (a UnixFTPGID) String() string {
	if str, ok := UnixFTPGID_Strings[a]; ok {
		return str
	}
	return "UnixFTPGID(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func UnixFTPGID_Add(p *radius.Packet, value UnixFTPGID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Unix_AddVendor(p, 11, a)
}

func UnixFTPGID_Get(p *radius.Packet) (value UnixFTPGID) {
	value, _ = UnixFTPGID_Lookup(p)
	return
}

func UnixFTPGID_Gets(p *radius.Packet) (values []UnixFTPGID, err error) {
	var i uint32
	for _, attr := range _Unix_GetsVendor(p, 11) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, UnixFTPGID(i))
	}
	return
}

func UnixFTPGID_Lookup(p *radius.Packet) (value UnixFTPGID, err error) {
	a, ok := _Unix_LookupVendor(p, 11)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = UnixFTPGID(i)
	return
}

func UnixFTPGID_Set(p *radius.Packet, value UnixFTPGID) (err error) {
	a := radius.NewInteger(uint32(value))
	return _Unix_SetVendor(p, 11, a)
}

func UnixFTPGID_Del(p *radius.Packet) {
	_Unix_DelVendor(p, 11)
}

func UnixFTPHome_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 12, a)
}

func UnixFTPHome_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 12, a)
}

func UnixFTPHome_Get(p *radius.Packet) (value []byte) {
	value, _ = UnixFTPHome_Lookup(p)
	return
}

func UnixFTPHome_GetString(p *radius.Packet) (value string) {
	value, _ = UnixFTPHome_LookupString(p)
	return
}

func UnixFTPHome_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Unix_GetsVendor(p, 12) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPHome_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Unix_GetsVendor(p, 12) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPHome_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Unix_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func UnixFTPHome_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Unix_LookupVendor(p, 12)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func UnixFTPHome_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 12, a)
}

func UnixFTPHome_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 12, a)
}

func UnixFTPHome_Del(p *radius.Packet) {
	_Unix_DelVendor(p, 12)
}

func UnixFTPShell_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 13, a)
}

func UnixFTPShell_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 13, a)
}

func UnixFTPShell_Get(p *radius.Packet) (value []byte) {
	value, _ = UnixFTPShell_Lookup(p)
	return
}

func UnixFTPShell_GetString(p *radius.Packet) (value string) {
	value, _ = UnixFTPShell_LookupString(p)
	return
}

func UnixFTPShell_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Unix_GetsVendor(p, 13) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPShell_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Unix_GetsVendor(p, 13) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPShell_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Unix_LookupVendor(p, 13)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func UnixFTPShell_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Unix_LookupVendor(p, 13)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func UnixFTPShell_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 13, a)
}

func UnixFTPShell_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 13, a)
}

func UnixFTPShell_Del(p *radius.Packet) {
	_Unix_DelVendor(p, 13)
}

func UnixFTPGroupNames_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 14, a)
}

func UnixFTPGroupNames_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 14, a)
}

func UnixFTPGroupNames_Get(p *radius.Packet) (value []byte) {
	value, _ = UnixFTPGroupNames_Lookup(p)
	return
}

func UnixFTPGroupNames_GetString(p *radius.Packet) (value string) {
	value, _ = UnixFTPGroupNames_LookupString(p)
	return
}

func UnixFTPGroupNames_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Unix_GetsVendor(p, 14) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPGroupNames_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Unix_GetsVendor(p, 14) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPGroupNames_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Unix_LookupVendor(p, 14)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func UnixFTPGroupNames_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Unix_LookupVendor(p, 14)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func UnixFTPGroupNames_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 14, a)
}

func UnixFTPGroupNames_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 14, a)
}

func UnixFTPGroupNames_Del(p *radius.Packet) {
	_Unix_DelVendor(p, 14)
}

func UnixFTPGroupIds_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 15, a)
}

func UnixFTPGroupIds_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_AddVendor(p, 15, a)
}

func UnixFTPGroupIds_Get(p *radius.Packet) (value []byte) {
	value, _ = UnixFTPGroupIds_Lookup(p)
	return
}

func UnixFTPGroupIds_GetString(p *radius.Packet) (value string) {
	value, _ = UnixFTPGroupIds_LookupString(p)
	return
}

func UnixFTPGroupIds_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _Unix_GetsVendor(p, 15) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPGroupIds_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _Unix_GetsVendor(p, 15) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func UnixFTPGroupIds_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _Unix_LookupVendor(p, 15)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func UnixFTPGroupIds_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _Unix_LookupVendor(p, 15)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func UnixFTPGroupIds_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 15, a)
}

func UnixFTPGroupIds_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _Unix_SetVendor(p, 15, a)
}

func UnixFTPGroupIds_Del(p *radius.Packet) {
	_Unix_DelVendor(p, 15)
}
