# golangci-lint v2 configuration
version: "2"

linters:
  default: standard
  settings:
    staticcheck:
      checks:
        - all
        - "-ST1000" # Disable package comment requirement
        - "-ST1003" # Disable naming convention (Id vs ID, etc)
        - "-ST1005" # Disable error string format check
        - "-ST1006" # Disable receiver name style check
        - "-ST1016" # Disable receiver name consistency check
        - "-ST1020" # Disable function comment format check
        - "-ST1021" # Disable type comment format check

issues:
  exclude-dirs:
    - pkg/xmlx
