#!/bin/sh

ps aux | grep admin.py | awk '{print $2}' | xargs  kill

python createdb.py -c radiusd.conf -i

cd console 
python admin.py & 
cd ..

sleep 4

python httptests/alls.py

sleep 4

echo "print any key to exist:"

read var1

ps aux | grep admin.py | awk '{print $2}' | xargs  kill
