#!/usr/bin/env bash


admin()
{
    pypy toughctl --admin --debug -c toughradius.conf
}


initdb()
{
    pypy toughctl --initdb -c toughradius.conf
}

case "$1" in

  admin)
    admin
  ;;

  initdb)
    initdb
  ;;

esac