#!/bin/sh
# /etc/rc.d/init.d/toughrad
#
# toughradius service script 
# https://github.com/talkincode/ToughRADIUS
#
# chkconfig: 345 91 05
# description: toughrad service
# processname: toughrad

# Source init functions
if [ -f /etc/rc.d/init.d/functions ]
then
    . /etc/rc.d/init.d/functions
fi

appdir=/opt/toughradius
rundir=/var/toughradius

start()
{
    if [ $( pgrep -f supervisord | wc -l ) -gt 0 ]
    then 
        supervisorctl start all 
    else 
        supervisord -c ${rundir}/supervisord.conf
    fi 
}

docker()
{
    if [ -f ${rundir}/install.log ]
    then
        sh ${appdir}/install/centos7-install.sh setup
    else
        start
    fi
}

stop()
{
    if [ $( pgrep -f supervisord | wc -l ) -gt 0 ]
    then 
        supervisorctl stop all
        supervisorctl shutdown
    else
        echo "supervisord not running"
    fi 
}

status()
{
    if [ $( pgrep -f supervisord | wc -l ) -gt 0 ]
    then 
        supervisorctl status
    else 
        echo "supervisord not running"
    fi 

}

restart()
{
    if [ $( pgrep -f supervisord | wc -l ) -gt 0 ]
    then 
        supervisorctl restart all
    else 
        supervisord -c ${rundir}/supervisord.conf
    fi 
}

upgrade()
{
    echo 'starting upgrade...' 
    cd ${appdir} && git pull origin master
    supervisorctl restart all
    supervisorctl status
    echo 'upgrade done'
}

startdb()
{
    /usr/bin/mysqld_safe --defaults-file=${rundir}/mysql/my.cnf --user=mysql &
}

stopdb()
{
    mysqladmin --defaults-file=${rundir}/mysql/my.cnf -uroot shutdown
}

backupdb()
{
    python /opt/toughradius/backupdb.py -c /var/toughradius/radiusd.json
}


case "$1" in

  start)
    start
  ;;
  
  stop)
    stop
  ;;
  
  status)
    status
  ;;    
  
  restart)
    restart
  ;;    
  
  upgrade)
    upgrade
  ;;  
  
  startdb)
    startdb
  ;; 
  
  stopdb)
    stopdb
  ;;  
  
  backupdb)
    backupdb
  ;;   
  
  docker)
    docker
  ;;        


  *)
    echo "Usage: $0 {start|stop|status|restart|upgrade|startdb|stopdb|backupdb|docker}"
  ;;

esac