// Code generated by radius-dict-gen. DO NOT EDIT.

package ikuai

import (
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_IKuai_VendorID = 10055
)

func _IKuai_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_IKuai_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _IKuai_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _IKuai_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _IKuai_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _IKuai_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _IKuai_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _IKuai_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _IKuai_AddVendor(p, typ, attr)
}

func _IKuai_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _IKuai_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

type RPUpstreamSpeedLimit uint32

var RPUpstreamSpeedLimit_Strings = map[RPUpstreamSpeedLimit]string{}

func (a RPUpstreamSpeedLimit) String() string {
	if str, ok := RPUpstreamSpeedLimit_Strings[a]; ok {
		return str
	}
	return "RPUpstreamSpeedLimit(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func RPUpstreamSpeedLimit_Add(p *radius.Packet, value RPUpstreamSpeedLimit) (err error) {
	a := radius.NewInteger(uint32(value))
	return _IKuai_AddVendor(p, 1, a)
}

func RPUpstreamSpeedLimit_Get(p *radius.Packet) (value RPUpstreamSpeedLimit) {
	value, _ = RPUpstreamSpeedLimit_Lookup(p)
	return
}

func RPUpstreamSpeedLimit_Gets(p *radius.Packet) (values []RPUpstreamSpeedLimit, err error) {
	var i uint32
	for _, attr := range _IKuai_GetsVendor(p, 1) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, RPUpstreamSpeedLimit(i))
	}
	return
}

func RPUpstreamSpeedLimit_Lookup(p *radius.Packet) (value RPUpstreamSpeedLimit, err error) {
	a, ok := _IKuai_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = RPUpstreamSpeedLimit(i)
	return
}

func RPUpstreamSpeedLimit_Set(p *radius.Packet, value RPUpstreamSpeedLimit) (err error) {
	a := radius.NewInteger(uint32(value))
	return _IKuai_SetVendor(p, 1, a)
}

func RPUpstreamSpeedLimit_Del(p *radius.Packet) {
	_IKuai_DelVendor(p, 1)
}

type RPDownstreamSpeedLimit uint32

var RPDownstreamSpeedLimit_Strings = map[RPDownstreamSpeedLimit]string{}

func (a RPDownstreamSpeedLimit) String() string {
	if str, ok := RPDownstreamSpeedLimit_Strings[a]; ok {
		return str
	}
	return "RPDownstreamSpeedLimit(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func RPDownstreamSpeedLimit_Add(p *radius.Packet, value RPDownstreamSpeedLimit) (err error) {
	a := radius.NewInteger(uint32(value))
	return _IKuai_AddVendor(p, 2, a)
}

func RPDownstreamSpeedLimit_Get(p *radius.Packet) (value RPDownstreamSpeedLimit) {
	value, _ = RPDownstreamSpeedLimit_Lookup(p)
	return
}

func RPDownstreamSpeedLimit_Gets(p *radius.Packet) (values []RPDownstreamSpeedLimit, err error) {
	var i uint32
	for _, attr := range _IKuai_GetsVendor(p, 2) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, RPDownstreamSpeedLimit(i))
	}
	return
}

func RPDownstreamSpeedLimit_Lookup(p *radius.Packet) (value RPDownstreamSpeedLimit, err error) {
	a, ok := _IKuai_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = RPDownstreamSpeedLimit(i)
	return
}

func RPDownstreamSpeedLimit_Set(p *radius.Packet, value RPDownstreamSpeedLimit) (err error) {
	a := radius.NewInteger(uint32(value))
	return _IKuai_SetVendor(p, 2, a)
}

func RPDownstreamSpeedLimit_Del(p *radius.Packet) {
	_IKuai_DelVendor(p, 2)
}

func RPHURL_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _IKuai_AddVendor(p, 3, a)
}

func RPHURL_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _IKuai_AddVendor(p, 3, a)
}

func RPHURL_Get(p *radius.Packet) (value []byte) {
	value, _ = RPHURL_Lookup(p)
	return
}

func RPHURL_GetString(p *radius.Packet) (value string) {
	value, _ = RPHURL_LookupString(p)
	return
}

func RPHURL_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _IKuai_GetsVendor(p, 3) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RPHURL_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _IKuai_GetsVendor(p, 3) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RPHURL_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _IKuai_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func RPHURL_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _IKuai_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func RPHURL_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _IKuai_SetVendor(p, 3, a)
}

func RPHURL_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _IKuai_SetVendor(p, 3, a)
}

func RPHURL_Del(p *radius.Packet) {
	_IKuai_DelVendor(p, 3)
}

func RPMOTM_Add(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _IKuai_AddVendor(p, 4, a)
}

func RPMOTM_AddString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _IKuai_AddVendor(p, 4, a)
}

func RPMOTM_Get(p *radius.Packet) (value []byte) {
	value, _ = RPMOTM_Lookup(p)
	return
}

func RPMOTM_GetString(p *radius.Packet) (value string) {
	value, _ = RPMOTM_LookupString(p)
	return
}

func RPMOTM_Gets(p *radius.Packet) (values [][]byte, err error) {
	var i []byte
	for _, attr := range _IKuai_GetsVendor(p, 4) {
		i = radius.Bytes(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RPMOTM_GetStrings(p *radius.Packet) (values []string, err error) {
	var i string
	for _, attr := range _IKuai_GetsVendor(p, 4) {
		i = radius.String(attr)
		if err != nil {
			return
		}
		values = append(values, i)
	}
	return
}

func RPMOTM_Lookup(p *radius.Packet) (value []byte, err error) {
	a, ok := _IKuai_LookupVendor(p, 4)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.Bytes(a)
	return
}

func RPMOTM_LookupString(p *radius.Packet) (value string, err error) {
	a, ok := _IKuai_LookupVendor(p, 4)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	value = radius.String(a)
	return
}

func RPMOTM_Set(p *radius.Packet, value []byte) (err error) {
	var a radius.Attribute
	a, err = radius.NewBytes(value)
	if err != nil {
		return
	}
	return _IKuai_SetVendor(p, 4, a)
}

func RPMOTM_SetString(p *radius.Packet, value string) (err error) {
	var a radius.Attribute
	a, err = radius.NewString(value)
	if err != nil {
		return
	}
	return _IKuai_SetVendor(p, 4, a)
}

func RPMOTM_Del(p *radius.Packet) {
	_IKuai_DelVendor(p, 4)
}

type RPMaxSessionsPerUser uint32

var RPMaxSessionsPerUser_Strings = map[RPMaxSessionsPerUser]string{}

func (a RPMaxSessionsPerUser) String() string {
	if str, ok := RPMaxSessionsPerUser_Strings[a]; ok {
		return str
	}
	return "RPMaxSessionsPerUser(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func RPMaxSessionsPerUser_Add(p *radius.Packet, value RPMaxSessionsPerUser) (err error) {
	a := radius.NewInteger(uint32(value))
	return _IKuai_AddVendor(p, 5, a)
}

func RPMaxSessionsPerUser_Get(p *radius.Packet) (value RPMaxSessionsPerUser) {
	value, _ = RPMaxSessionsPerUser_Lookup(p)
	return
}

func RPMaxSessionsPerUser_Gets(p *radius.Packet) (values []RPMaxSessionsPerUser, err error) {
	var i uint32
	for _, attr := range _IKuai_GetsVendor(p, 5) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, RPMaxSessionsPerUser(i))
	}
	return
}

func RPMaxSessionsPerUser_Lookup(p *radius.Packet) (value RPMaxSessionsPerUser, err error) {
	a, ok := _IKuai_LookupVendor(p, 5)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = RPMaxSessionsPerUser(i)
	return
}

func RPMaxSessionsPerUser_Set(p *radius.Packet, value RPMaxSessionsPerUser) (err error) {
	a := radius.NewInteger(uint32(value))
	return _IKuai_SetVendor(p, 5, a)
}

func RPMaxSessionsPerUser_Del(p *radius.Packet) {
	_IKuai_DelVendor(p, 5)
}
