version: "3"
services:
  tsdb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: "tsdb"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: toughradius
      POSTGRES_USER: toughradius
      POSTGRES_PASSWORD: toughradius
    volumes:
      - tsdb-volume:/home/postgres/pgdata/data
    networks:
      tr_network:

  loki:
    image: grafana/loki:2.7.1
    container_name: "loki"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
    user: "1000"
    environment:
    - TZ=Asia/Shanghai
    - LANG=zh_CN.UTF-8
    command: -config.file=/etc/loki/config.yml
    volumes:
      - /etc/loki/config.yml:/etc/loki/config.yml
      - loki-volume:/loki
    ports:
      - "3100:3100"
    networks:
      tr_network:

  toughradius:
    depends_on:
      - 'tsdb'
    image: talkincode/toughradius:latest
    container_name: "toughradius"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
    ports:
      - "1816:1816"
      - "1817:1817"
      - "1818:1818"
      - "1819:1819"
      - "1812:1812"
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "1914:1914/udp"
    volumes:
      - toughradius-volume:/var/toughradius
    environment:
      - GODEBUG=x509ignoreCN=0
      - TOUGHRADIUS_SYSTEM_DEBUG=off
      - TOUGHRADIUS_DB_HOST=tsdb
      - TOUGHRADIUS_DB_NAME=toughradius
      - TOUGHRADIUS_DB_USER=toughradius
      - TOUGHRADIUS_DB_PWD=toughradius
      - TOUGHRADIUS_RADIUS_DEBUG=off
      - TOUGHRADIUS_RADIUS_ENABLED=on
      - TOUGHRADIUS_TR069_WEB_TLS=on
      - TOUGHRADIUS_LOKI_JOB=toughradius
      - TOUGHRADIUS_LOKI_SERVER=http://loki:3100
      - TOUGHRADIUS_LOKI_ENABLE=true
      - TOUGHRADIUS_LOGGER_MODE=production
      - TOUGHRADIUS_LOGGER_FILE_ENABLE=true
    networks:
      - tr_network

networks:
  tr_network:

volumes:
  tsdb-volume:
  loki-volume:
  toughradius-volume: