// Code generated by radius-dict-gen. DO NOT EDIT.

package pfSense

import (
	"strconv"

	"layeh.com/radius"
	"layeh.com/radius/rfc2865"
)

const (
	_PfSense_VendorID = 13644
)

func _PfSense_AddVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	var vsa radius.Attribute
	vendor := make(radius.Attribute, 2+len(attr))
	vendor[0] = typ
	vendor[1] = byte(len(vendor))
	copy(vendor[2:], attr)
	vsa, err = radius.NewVendorSpecific(_PfSense_VendorID, vendor)
	if err != nil {
		return
	}
	p.Add(rfc2865.VendorSpecific_Type, vsa)
	return
}

func _PfSense_GetsVendor(p *radius.Packet, typ byte) (values []radius.Attribute) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _PfSense_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				values = append(values, vsa[2:int(vsaLen)])
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _PfSense_LookupVendor(p *radius.Packet, typ byte) (attr radius.Attribute, ok bool) {
	for _, avp := range p.Attributes {
		if avp.Type != rfc2865.VendorSpecific_Type {
			continue
		}
		attr := avp.Attribute
		vendorID, vsa, err := radius.VendorSpecific(attr)
		if err != nil || vendorID != _PfSense_VendorID {
			continue
		}
		for len(vsa) >= 3 {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				break
			}
			if vsaTyp == typ {
				return vsa[2:int(vsaLen)], true
			}
			vsa = vsa[int(vsaLen):]
		}
	}
	return
}

func _PfSense_SetVendor(p *radius.Packet, typ byte, attr radius.Attribute) (err error) {
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _PfSense_VendorID {
			i++
			continue
		}
		for j := 0; len(vsa[j:]) >= 3; {
			vsaTyp, vsaLen := vsa[0], vsa[1]
			if int(vsaLen) > len(vsa[j:]) || vsaLen < 3 {
				i++
				break
			}
			if vsaTyp == typ {
				vsa = append(vsa[:j], vsa[j+int(vsaLen):]...)
			}
			j += int(vsaLen)
		}
		if len(vsa) > 0 {
			copy(avp.Attribute[4:], vsa)
			i++
		} else {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+i:]...)
		}
	}
	return _PfSense_AddVendor(p, typ, attr)
}

func _PfSense_DelVendor(p *radius.Packet, typ byte) {
vsaLoop:
	for i := 0; i < len(p.Attributes); {
		avp := p.Attributes[i]
		if avp.Type != rfc2865.VendorSpecific_Type {
			i++
			continue
		}
		vendorID, vsa, err := radius.VendorSpecific(avp.Attribute)
		if err != nil || vendorID != _PfSense_VendorID {
			i++
			continue
		}
		offset := 0
		for len(vsa[offset:]) >= 3 {
			vsaTyp, vsaLen := vsa[offset], vsa[offset+1]
			if int(vsaLen) > len(vsa) || vsaLen < 3 {
				continue vsaLoop
			}
			if vsaTyp == typ {
				copy(vsa[offset:], vsa[offset+int(vsaLen):])
				vsa = vsa[:len(vsa)-int(vsaLen)]
			} else {
				offset += int(vsaLen)
			}
		}
		if offset == 0 {
			p.Attributes = append(p.Attributes[:i], p.Attributes[i+1:]...)
		} else {
			i++
		}
	}
	return
}

type PfSenseBandwidthMaxUp uint32

var PfSenseBandwidthMaxUp_Strings = map[PfSenseBandwidthMaxUp]string{}

func (a PfSenseBandwidthMaxUp) String() string {
	if str, ok := PfSenseBandwidthMaxUp_Strings[a]; ok {
		return str
	}
	return "PfSenseBandwidthMaxUp(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PfSenseBandwidthMaxUp_Add(p *radius.Packet, value PfSenseBandwidthMaxUp) (err error) {
	a := radius.NewInteger(uint32(value))
	return _PfSense_AddVendor(p, 1, a)
}

func PfSenseBandwidthMaxUp_Get(p *radius.Packet) (value PfSenseBandwidthMaxUp) {
	value, _ = PfSenseBandwidthMaxUp_Lookup(p)
	return
}

func PfSenseBandwidthMaxUp_Gets(p *radius.Packet) (values []PfSenseBandwidthMaxUp, err error) {
	var i uint32
	for _, attr := range _PfSense_GetsVendor(p, 1) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PfSenseBandwidthMaxUp(i))
	}
	return
}

func PfSenseBandwidthMaxUp_Lookup(p *radius.Packet) (value PfSenseBandwidthMaxUp, err error) {
	a, ok := _PfSense_LookupVendor(p, 1)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PfSenseBandwidthMaxUp(i)
	return
}

func PfSenseBandwidthMaxUp_Set(p *radius.Packet, value PfSenseBandwidthMaxUp) (err error) {
	a := radius.NewInteger(uint32(value))
	return _PfSense_SetVendor(p, 1, a)
}

func PfSenseBandwidthMaxUp_Del(p *radius.Packet) {
	_PfSense_DelVendor(p, 1)
}

type PfSenseBandwidthMaxDown uint32

var PfSenseBandwidthMaxDown_Strings = map[PfSenseBandwidthMaxDown]string{}

func (a PfSenseBandwidthMaxDown) String() string {
	if str, ok := PfSenseBandwidthMaxDown_Strings[a]; ok {
		return str
	}
	return "PfSenseBandwidthMaxDown(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PfSenseBandwidthMaxDown_Add(p *radius.Packet, value PfSenseBandwidthMaxDown) (err error) {
	a := radius.NewInteger(uint32(value))
	return _PfSense_AddVendor(p, 2, a)
}

func PfSenseBandwidthMaxDown_Get(p *radius.Packet) (value PfSenseBandwidthMaxDown) {
	value, _ = PfSenseBandwidthMaxDown_Lookup(p)
	return
}

func PfSenseBandwidthMaxDown_Gets(p *radius.Packet) (values []PfSenseBandwidthMaxDown, err error) {
	var i uint32
	for _, attr := range _PfSense_GetsVendor(p, 2) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PfSenseBandwidthMaxDown(i))
	}
	return
}

func PfSenseBandwidthMaxDown_Lookup(p *radius.Packet) (value PfSenseBandwidthMaxDown, err error) {
	a, ok := _PfSense_LookupVendor(p, 2)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PfSenseBandwidthMaxDown(i)
	return
}

func PfSenseBandwidthMaxDown_Set(p *radius.Packet, value PfSenseBandwidthMaxDown) (err error) {
	a := radius.NewInteger(uint32(value))
	return _PfSense_SetVendor(p, 2, a)
}

func PfSenseBandwidthMaxDown_Del(p *radius.Packet) {
	_PfSense_DelVendor(p, 2)
}

type PfSenseMaxTotalOctets uint32

var PfSenseMaxTotalOctets_Strings = map[PfSenseMaxTotalOctets]string{}

func (a PfSenseMaxTotalOctets) String() string {
	if str, ok := PfSenseMaxTotalOctets_Strings[a]; ok {
		return str
	}
	return "PfSenseMaxTotalOctets(" + strconv.FormatUint(uint64(a), 10) + ")"
}

func PfSenseMaxTotalOctets_Add(p *radius.Packet, value PfSenseMaxTotalOctets) (err error) {
	a := radius.NewInteger(uint32(value))
	return _PfSense_AddVendor(p, 3, a)
}

func PfSenseMaxTotalOctets_Get(p *radius.Packet) (value PfSenseMaxTotalOctets) {
	value, _ = PfSenseMaxTotalOctets_Lookup(p)
	return
}

func PfSenseMaxTotalOctets_Gets(p *radius.Packet) (values []PfSenseMaxTotalOctets, err error) {
	var i uint32
	for _, attr := range _PfSense_GetsVendor(p, 3) {
		i, err = radius.Integer(attr)
		if err != nil {
			return
		}
		values = append(values, PfSenseMaxTotalOctets(i))
	}
	return
}

func PfSenseMaxTotalOctets_Lookup(p *radius.Packet) (value PfSenseMaxTotalOctets, err error) {
	a, ok := _PfSense_LookupVendor(p, 3)
	if !ok {
		err = radius.ErrNoAttribute
		return
	}
	var i uint32
	i, err = radius.Integer(a)
	if err != nil {
		return
	}
	value = PfSenseMaxTotalOctets(i)
	return
}

func PfSenseMaxTotalOctets_Set(p *radius.Packet, value PfSenseMaxTotalOctets) (err error) {
	a := radius.NewInteger(uint32(value))
	return _PfSense_SetVendor(p, 3, a)
}

func PfSenseMaxTotalOctets_Del(p *radius.Packet) {
	_PfSense_DelVendor(p, 3)
}
